# Datenanalyse CIS-Daten.xlsx
* Dateipfad der Excel ändern!!!

In [17]:
import pandas as pd

In [18]:
pd.set_option('display.max_columns', None)

In [19]:
df = pd.read_excel("CIS-Daten.xlsx")
print(df.shape)
df.head()

(2800, 183)

,TOURNR,BEZEICHNUNG,BEMERKUNG,HAUPTTOUR,TOURENART,SENDART,STARTDATUM,STARTKENNUNG,STARTNAME1,STARTNAME2,STARTNAME3,STARTLAND,STARTPLZ,STARTORT,STARTORTSTEIL,STARTORTZUSATZ,STARTSTRASSE,STARTINFO,STARTRELATION,STARTERMITTLUNG,STARTUTCABWEICHUNG,ANKUNFTDATUM,ANKUNFTKENNUNG,ANKUNFTNAME1,ANKUNFTNAME2,ANKUNFTNAME3,ANKUNFTLAND,ANKUNFTPLZ,ANKUNFTORT,ANKUNFTORTSTEIL,ANKUNFTORTZUSATZ,ANKUNFTSTRASSE,ANKUNFTINFO,ANKUNFTRELATION,ANKUNFTERMITTLUNG,ANKUNFTUTCABWEICHUNG,ENTFERNUNG,MAUT_KM,MAUT_KM_MANUELL,EMPFSPED,LKWNR,LKW_KENNZ,ANHNR,ANH_KENNZ,FAHRER,FAHRERNAME,BEGLEITER,BEGLEITERNAME,GERAET1,GERAET1_KENNZ,GERAET2,GERAET2_KENNZ,BUCHFLAG,DRUCKSTATUS,FRFUEHRER,FRZAHLER,GEWICHT,VOLUMEN,LADEMETER,WARENWERT,ANZSTUECK,ANZCOLLI,ANZPAL1,ANZPAL2,ANZPAL3,SOLL_ZEIT,ANZSENDUNGEN,WB1,WB2,SONST1,SONST2,FF_PROJEKT,FF_PROJEKTNR,FF_NR,FF_FAKTNR,FF_MATCHCODE,FF_PREISBILD,FF_DRUCKFLAG,FF_TARIF,FF_MARGE,FF_PREISTARIF,FF_PREISVEREINB,FF_ZEIT,FF_TEXTFLAG,FF_ENTFERNUNG,FF_WC,FZ_PROJEKT,FZ_PROJEKTNR,FZ_NR,FZ_FAKTNR,FZ_MATCHCODE,FZ_PREISBILD,FZ_DRUCKFLAG,FZ_TARIF,FZ_MARGE,FZ_PREISTARIF,FZ_PREISVEREINB,FZ_ZEIT,FZ_TEXTFLAG,FZ_ENTFERNUNG,FZ_WC,GRENZELAND,GRENZEPLZ,GRENZEORT,NL,DISPO_GRP,FZG_GRP,BEARBSTATUS,ANFORDERUNG_FS,ANFORDERUNG_ADR,ANFORDERUNG_SONST,ANFORDERUNG_KFZ,PRIOR_PLAN,PRIOR_EINSATZ,TELEMATIK_ID,TELEMATIK_EXPORT_DATUM,STATIONSSTATUS,KALKULIERTE_KOSTEN,ERLOES,LEERTOUR,EXPFLAG,PLANTOUR,KMSTART,KMANKUNFT,FELDEIGENSCHAFTEN,BEARBEITUNGSKENNZEICHEN,LSTELLPLATZ_ID,ERFASSDATUM,ERFASSNUTZER,AENDERDATUM,AENDERNUTZER,TATS_GEWICHT,STELLPLAETZE,KALKULATIONSART,KALKULATIONSLEVEL,SPERRESTATUS,EMISSION_CO2,ANZSENDPOS,TATS_GEWICHT_MANUELL,VOLUMEN_MANUELL,LADEMETER_MANUELL,STELLPLAETZE_MANUELL,MAUT_KOSTEN_MANUELL,EXTERNE_NUMMER,TELEMATIKWORKFLOWID,NUMMER,TOUR,TOURSTATION_ID,TYP,TOURSTATIONAKTION_ID,ANKUNFT,ABFAHRT,UTCABWEICHUNG,ENTFERNUNG_1,DIFFERENZENTFERNUNG,ADRESSE,NAME1,NAME2,LAND,PLZ,ORT,ORTSTEIL,STRASSE,GEOX,GEOY,GEOSTATUS,TATS_ANKUNFT,TATS_ABFAHRT,ISTZEITSTATUS,ANKUNFT_SOLLVON,ANKUNFT_SOLLBIS,INFOTEXT,FEST,FLAGS,LADEMETER_1,ANFORDERUNG_FS_1,ANFORDERUNG_ADR_1,ANFORDERUNG_SONST_1,ANFORDERUNG_KFZ_1,ERFASSDATUM_1,ERFASSNUTZER_1,AENDERDATUM_1,AENDERNUTZER_1
0,H/42374,Greif,NaN,NaN,0,NaN,02.03.2026 06:00,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,NaN,D,20457,Hamburg,NaN,NaN,Brandenburger Str. 12,NaN,NaN,0,1,02.03.2026 09:23,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,NaN,D,20457,Hamburg,NaN,NaN,Brandenburger Str. 12,NaN,NaN,0,1,NaN,8.4,NaN,NaN,92564-14,Plo-TS856,NaN,NaN,317.0,"Hesse, Sven-Erik",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22926-htsahre,NaN,6480.0,128.6604,0,0,450,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,-2,NaN,NaN,NaN,0.0,NaN,NaN,35.83,1,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,15.72,NaN,NaN,NaN,NaN,1,Greif,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129,0,400.94,1.0,0,NaN,NaN,NaN,NaN,0.0,NaN,26.02.2026 14:32,FS,02.03.2026 17:55,cisfleetsrv,6480.0,0.0,0,0,NaN,0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,H/42374,553624,1,NaN,02.03.2026 06:00,02.03.2026 06:00,1,0.00,0.00,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,D,20457.0,Hamburg,NaN,Brandenburger Str. 12,9.98632,53.52348,2.0,02.03.2026 06:59,02.03.2026 06:59,10,NaN,NaN,NaN,1.0,0.0,0.0,NaN,NaN,NaN,NaN,01.03.2026 11:16,FS,01.03.2026 11:16,FS
1,H/42374,Greif,NaN,NaN,0,NaN,02.03.2026 06:00,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,NaN,D,20457,Hamburg,NaN,NaN,Brandenburger Str. 12,NaN,NaN,0,1,02.03.2026 09:23,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,NaN,D,20457,Hamburg,NaN,NaN,Brandenburger Str. 12,NaN,NaN,0,1,NaN,8.4,NaN,NaN,92564-14,Plo-TS856,NaN,NaN,317.0,"Hesse, Sven-Erik",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22926-htsahre,NaN,6480.0,128.6604,0,0,450,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,-2,NaN,NaN,NaN,0.0,NaN,NaN,35.83,1,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,15.72,NaN,NaN,NaN,NaN,1,Greif,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129,0,400.94,1.0,0,NaN,NaN,NaN,NaN,0.0,NaN,26.02.2026 14:32,FS,02.03.2026 17:55,cisfleetsrv,6480.0,0.0,0,0,NaN,0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,H/42374,553625,4,NaN,02.03.2026 06:00,02.03.2026 06:30,1,0.00,7.86,20457-GreifHamb,Greif Packaging Germany GmbH,NaN,D,20457.0,Hamburg,NaN,Brandenburger Straße 12,9.98632,53.52348,2.0,02.03.2026 07:00,02.03.2026 09:28,10,29.12.1899,29.12.1899,NaN,1.0,0.0,0.0,NaN,NaN,NaN,NaN,01.03.2026 11:16,FS,01.03.2026 11:16,FS
2,H/42374,Greif,NaN,NaN,0,NaN,02.03.2026 06:00,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,NaN,D,20457,Hamburg,NaN,NaN,Brandenburger Str. 12,NaN,NaN,0,1,02.03.2026 09:23,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,NaN,D,20457,Hamburg,NaN,NaN,Brandenburger Str. 12,NaN,NaN,0,1,NaN,8.4,NaN,NaN,92564-14,Plo-TS856,NaN,NaN,317.0,"Hesse, Sven-Erik",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22926-htsahre,NaN,6480.0,128.6604,0,0,450,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,-2,NaN,NaN,NaN,0.0,NaN,NaN,35.83,1,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,15.72,NaN,NaN,NaN,NaN,1,Greif,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129,0,400.94,1.0,0,NaN,NaN,NaN,NaN,0.0,NaN,26.02.2026 14:32,FS,02.03.2026 17:55,cisfleetsrv,6480.0,0.0,0,0,NaN,0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,H/42374,553626,8,NaN,02.03.2026 06:49,02.03.2026 07:19,1,7.86,10.05,NaN,Shell Deutschland GmbH,NaN,D,20457.0,Hamburg,NaN,Worthdamm 32 Building: Grasbrook Lubrica,9.99383,53.54751,3.0,02.03.2026 07:18,02.03.2026 09:30,10,29.12.1899,29.12.1899,NaN,1.0,0.0,0.0,NaN,NaN,NaN,NaN,01.03.2026 11:16,FS,01.03.2026 11:16,FS
3,H/42374,Greif,NaN,NaN,0,NaN,02.03.2026 06:00,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,NaN,D,20457,Hamburg,NaN,NaN,Brandenburger Str. 12,NaN,NaN,0,1,02.03.2026 09:23,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,NaN,D,20457,Hamburg,NaN,NaN,Brandenburger Str. 12,NaN,NaN,0,1,NaN,8.4,NaN,NaN,92564-14,Plo-TS856,NaN,NaN,317.0,"Hesse, Sven-Erik",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22926-htsahre,NaN,6480.0,128.6604,0,0,450,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,-2,NaN,NaN,NaN,0.0,NaN,NaN,35.83,1,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,15.72,NaN,NaN,NaN,NaN,1,Greif,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129,0,400.94,1.0,0,NaN,NaN,NaN,NaN,0.0,NaN,26.02.2026 14:32,FS,02.03.2026 17:55,cisfleetsrv,6480.0,0.0,0,0,NaN,0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,H/42374,553634,4,NaN,02.03.2026 07:41,02.03.2026 08:11,1,17.91,7.86,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,D,20457.0,Hamburg,NaN,Brandenburger Str. 12,9.98632,53.52348,2.0,02.03.2026 09:56,02.03.2026 16:25,10,29.12.1899,29.12.1899,NaN,1.0,0.0,0.0,NaN,NaN,NaN,NaN,01.03.2026 11:16,FS,01.03.2026 11:16,FS
4,H/42374,Greif,NaN,NaN,0,NaN,02.03.2026 06:00,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,NaN,D,20457,Hamburg,NaN,NaN,Brandenburger Str. 12,NaN,NaN,0,1,02.03.2026 09:23,20457-GreifMafi,Greif Packaging Germany GmbH,NaN,NaN,D,20457,Hamburg,NaN,NaN,Brandenburger Str. 12,NaN,NaN,0,1,NaN,8.4,NaN,NaN,92564-14,Plo-TS856,NaN,NaN,317.0,"Hesse, Sven-Erik",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22926-htsahre,NaN,6480.0,128.6604,0,0,450,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,-2,NaN,NaN,NaN,0.0,NaN,NaN,35.83,1,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,15.72,NaN,NaN,NaN,NaN,1,Greif,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129,0,400.94,1.0,0,NaN,NaN,NaN,NaN,0.0,NaN,26.02.2026 14:32,FS,02.03.2026 17:55,cisfleetsrv,6480.0,0.0,0,0,NaN,0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,H/42374,553635,8,NaN,02.03.2026 08:31,02.03.2026 09:01,1,25.77,10.05,NaN,Shell Deutschland GmbH,NaN,D,20457.0,Hamburg,NaN,Worthdamm 32 Building: Grasbrook Lubrica,9.99383,53.54751,3.0,02.03.2026 11:16,02.03.2026 17:15,6,29.12.1899,29.12.1899,NaN,1.0,0.0,0.0,NaN,NaN,NaN,NaN,01.03.2026 11:16,FS,01.03.2026 11:16,FS

In [20]:
df_filtered = df[['LKWNR', 'FAHRERNAME', 'TOURNR', 'TOURSTATION_ID', 'NAME1', 'ANKUNFT_SOLLVON', 'ANKUNFT_SOLLBIS', 'ANKUNFT', 'ANKUNFTDATUM', 'TATS_ANKUNFT', 'STARTDATUM','ABFAHRT',  'TATS_ABFAHRT', 'ISTZEITSTATUS', 'PLZ', 'ORT', 'STRASSE', 'GEOX', 'GEOY']]
df_filtered.head()

,LKWNR,FAHRERNAME,TOURNR,TOURSTATION_ID,NAME1,ANKUNFT_SOLLVON,ANKUNFT_SOLLBIS,ANKUNFT,ANKUNFTDATUM,TATS_ANKUNFT,STARTDATUM,ABFAHRT,TATS_ABFAHRT,ISTZEITSTATUS,PLZ,ORT,STRASSE,GEOX,GEOY
0,92564-14,"Hesse, Sven-Erik",H/42374,553624,Greif Packaging Germany GmbH,NaN,NaN,02.03.2026 06:00,02.03.2026 09:23,02.03.2026 06:59,02.03.2026 06:00,02.03.2026 06:00,02.03.2026 06:59,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
1,92564-14,"Hesse, Sven-Erik",H/42374,553625,Greif Packaging Germany GmbH,29.12.1899,29.12.1899,02.03.2026 06:00,02.03.2026 09:23,02.03.2026 07:00,02.03.2026 06:00,02.03.2026 06:30,02.03.2026 09:28,10,20457.0,Hamburg,Brandenburger Straße 12,9.98632,53.52348
2,92564-14,"Hesse, Sven-Erik",H/42374,553626,Shell Deutschland GmbH,29.12.1899,29.12.1899,02.03.2026 06:49,02.03.2026 09:23,02.03.2026 07:18,02.03.2026 06:00,02.03.2026 07:19,02.03.2026 09:30,10,20457.0,Hamburg,Worthdamm 32 Building: Grasbrook Lubrica,9.99383,53.54751
3,92564-14,"Hesse, Sven-Erik",H/42374,553634,Greif Packaging Germany GmbH,29.12.1899,29.12.1899,02.03.2026 07:41,02.03.2026 09:23,02.03.2026 09:56,02.03.2026 06:00,02.03.2026 08:11,02.03.2026 16:25,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
4,92564-14,"Hesse, Sven-Erik",H/42374,553635,Shell Deutschland GmbH,29.12.1899,29.12.1899,02.03.2026 08:31,02.03.2026 09:23,02.03.2026 11:16,02.03.2026 06:00,02.03.2026 09:01,02.03.2026 17:15,6,20457.0,Hamburg,Worthdamm 32 Building: Grasbrook Lubrica,9.99383,53.54751

In [21]:
df_filtered.tail()

,LKWNR,FAHRERNAME,TOURNR,TOURSTATION_ID,NAME1,ANKUNFT_SOLLVON,ANKUNFT_SOLLBIS,ANKUNFT,ANKUNFTDATUM,TATS_ANKUNFT,STARTDATUM,ABFAHRT,TATS_ABFAHRT,ISTZEITSTATUS,PLZ,ORT,STRASSE,GEOX,GEOY
2795,92560-2,"Teme, Abdoulaye",H/42758,557896,Greif Packaging Germany GmbH,NaN,NaN,07.04.2026 06:00,07.04.2026 11:52,07.04.2026 06:16,07.04.2026 06:00,07.04.2026 06:00,07.04.2026 06:16,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
2796,92560-2,"Teme, Abdoulaye",H/42758,557897,Lubrizol Deutschland GmbH,07.04.2026,07.04.2026 23:59,07.04.2026 06:57,07.04.2026 11:52,07.04.2026 07:32,07.04.2026 06:00,07.04.2026 07:27,07.04.2026 09:26,10,22113.0,Hamburg,Billbrookdeich 157,10.09782,53.53610
2797,92560-2,"Teme, Abdoulaye",H/42758,557899,Greif Packaging Germany GmbH,29.12.1899,29.12.1899,07.04.2026 07:53,07.04.2026 11:52,07.04.2026 10:13,07.04.2026 06:00,07.04.2026 08:23,07.04.2026 10:41,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
2798,92560-2,"Teme, Abdoulaye",H/42758,557900,Blue Cube Germany GmbH Stade,29.12.1899,29.12.1899,07.04.2026 09:52,07.04.2026 11:52,07.04.2026 13:47,07.04.2026 06:00,07.04.2026 10:22,07.04.2026 15:18,10,21683.0,Stade,Buetzflethersand,9.51017,53.64711
2799,92560-2,"Teme, Abdoulaye",H/42758,557898,Greif Packaging Germany GmbH,NaN,NaN,07.04.2026 11:52,07.04.2026 11:52,07.04.2026 10:42,07.04.2026 06:00,07.04.2026 11:52,07.04.2026 11:33,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348

In [22]:
df_filtered.columns = df_filtered.columns.str.lower()
df_filtered.head()

,lkwnr,fahrername,tournr,tourstation_id,name1,ankunft_sollvon,ankunft_sollbis,ankunft,ankunftdatum,tats_ankunft,startdatum,abfahrt,tats_abfahrt,istzeitstatus,plz,ort,strasse,geox,geoy
0,92564-14,"Hesse, Sven-Erik",H/42374,553624,Greif Packaging Germany GmbH,NaN,NaN,02.03.2026 06:00,02.03.2026 09:23,02.03.2026 06:59,02.03.2026 06:00,02.03.2026 06:00,02.03.2026 06:59,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
1,92564-14,"Hesse, Sven-Erik",H/42374,553625,Greif Packaging Germany GmbH,29.12.1899,29.12.1899,02.03.2026 06:00,02.03.2026 09:23,02.03.2026 07:00,02.03.2026 06:00,02.03.2026 06:30,02.03.2026 09:28,10,20457.0,Hamburg,Brandenburger Straße 12,9.98632,53.52348
2,92564-14,"Hesse, Sven-Erik",H/42374,553626,Shell Deutschland GmbH,29.12.1899,29.12.1899,02.03.2026 06:49,02.03.2026 09:23,02.03.2026 07:18,02.03.2026 06:00,02.03.2026 07:19,02.03.2026 09:30,10,20457.0,Hamburg,Worthdamm 32 Building: Grasbrook Lubrica,9.99383,53.54751
3,92564-14,"Hesse, Sven-Erik",H/42374,553634,Greif Packaging Germany GmbH,29.12.1899,29.12.1899,02.03.2026 07:41,02.03.2026 09:23,02.03.2026 09:56,02.03.2026 06:00,02.03.2026 08:11,02.03.2026 16:25,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
4,92564-14,"Hesse, Sven-Erik",H/42374,553635,Shell Deutschland GmbH,29.12.1899,29.12.1899,02.03.2026 08:31,02.03.2026 09:23,02.03.2026 11:16,02.03.2026 06:00,02.03.2026 09:01,02.03.2026 17:15,6,20457.0,Hamburg,Worthdamm 32 Building: Grasbrook Lubrica,9.99383,53.54751

Spalten `ankunft` und `abfahrt` sind konsistent: Ankunft ist immer vor Abfahrt

In [23]:
df_filtered[df_filtered.ankunft > df_filtered.abfahrt]

Empty DataFrame
Columns: [lkwnr, fahrername, tournr, tourstation_id, name1, ankunft_sollvon, ankunft_sollbis, ankunft, ankunftdatum, tats_ankunft, startdatum, abfahrt, tats_abfahrt, istzeitstatus, plz, ort, strasse, geox, geoy]
Index: []

Spalten `tats_ankunft` und `tats_abfahrt` nicht konsistent: in 152 Fällen ist Ankunft später als Abfahrt

In [24]:
df_filtered[df_filtered.tats_ankunft > df_filtered.tats_abfahrt]

,lkwnr,fahrername,tournr,tourstation_id,name1,ankunft_sollvon,ankunft_sollbis,ankunft,ankunftdatum,tats_ankunft,startdatum,abfahrt,tats_abfahrt,istzeitstatus,plz,ort,strasse,geox,geoy
12,92564-8,"Szmajdewicz, Marcin",H/42375,553616,Greif Packaging Germany GmbH,NaN,NaN,02.03.2026 15:42,02.03.2026 15:42,02.03.2026 18:45,02.03.2026 06:00,02.03.2026 15:42,02.03.2026 14:49,9,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
464,92564-14,"Hesse, Sven-Erik",H/42430,554309,Shell Deutschland GmbH,NaN,NaN,06.03.2026 08:31,06.03.2026 11:51,06.03.2026 08:31,06.03.2026 06:00,06.03.2026 08:31,06.03.2026 01:02,10,20457.0,Hamburg,Worthdamm 32 Building: Grasbrook Lubrica,9.99383,53.54751
564,Mafi,"Stoffer, Andreas",H/42441,554625,Greif Packaging Germany GmbH,03.03.2026,31.03.2026 23:59,10.03.2026 07:00,10.03.2026 16:30,10.03.2026 14:38,10.03.2026 06:00,10.03.2026 07:05,10.03.2026 14:23,8,20457.0,Hamburg,Brandenburger Straße 12,9.98632,53.52348
565,Mafi,"Stoffer, Andreas",H/42441,554626,Greif Packaging Germany GmbH,03.03.2026,31.03.2026 23:59,10.03.2026 07:05,10.03.2026 16:30,10.03.2026 14:43,10.03.2026 06:00,10.03.2026 07:20,10.03.2026 14:38,8,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
566,Mafi,"Stoffer, Andreas",H/42441,554627,Greif Packaging Germany GmbH,03.03.2026,31.03.2026 23:59,10.03.2026 07:20,10.03.2026 16:30,10.03.2026 14:58,10.03.2026 06:00,10.03.2026 07:25,10.03.2026 14:37,8,20457.0,Hamburg,Brandenburger Straße 12,9.98632,53.52348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2364,PLÖ-TS859,"Krüger, Alexander",H/42646,557156,Hywax GmbH,NaN,NaN,31.03.2026 00:36,30.03.2026 16:00,30.03.2026 11:10,30.03.2026 06:00,31.03.2026 00:36,30.03.2026 04:51,10,20457.0,Hamburg,Worthdamm 13-27,9.98213,53.53497
2689,Mafi,"Mirzaie, Azar",H/42714,558015,Greif Packaging Germany GmbH,31.03.2026,28.04.2026 23:59,07.04.2026 06:55,07.04.2026 15:10,07.04.2026 08:35,07.04.2026 05:40,07.04.2026 07:00,07.04.2026 07:13,8,20457.0,Hamburg,Brandenburger Straße 12,9.98632,53.52348
2690,Mafi,"Mirzaie, Azar",H/42714,558016,Greif Packaging Germany GmbH,31.03.2026,28.04.2026 23:59,07.04.2026 07:00,07.04.2026 15:10,07.04.2026 08:40,07.04.2026 05:40,07.04.2026 07:15,07.04.2026 07:14,8,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
2693,Mafi,"Mirzaie, Azar",H/42714,558019,Greif Packaging Germany GmbH,31.03.2026,28.04.2026 23:59,07.04.2026 07:35,07.04.2026 15:10,07.04.2026 11:32,07.04.2026 05:40,07.04.2026 07:40,07.04.2026 10:58,8,20457.0,Hamburg,Brandenburger Straße 12,9.98632,53.52348
2694,Mafi,"Mirzaie, Azar",H/42714,558020,Greif Packaging Germany GmbH,31.03.2026,28.04.2026 23:59,07.04.2026 07:40,07.04.2026 15:10,07.04.2026 11:37,07.04.2026 05:40,07.04.2026 07:55,07.04.2026 10:59,8,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348

In [25]:
df_filtered[df_filtered.startdatum > df_filtered.ankunftdatum]

Empty DataFrame
Columns: [lkwnr, fahrername, tournr, tourstation_id, name1, ankunft_sollvon, ankunft_sollbis, ankunft, ankunftdatum, tats_ankunft, startdatum, abfahrt, tats_abfahrt, istzeitstatus, plz, ort, strasse, geox, geoy]
Index: []

Spalten `ankunftdatum` und `tats_abfahrt` nicht konsistent: in 2307 Fällen ist Ankunft später als Abfahrt
* unklar ist auch was `ankunftdatum` genau beschreibt

In [26]:
df_filtered[df_filtered.ankunftdatum > df_filtered.tats_abfahrt]

,lkwnr,fahrername,tournr,tourstation_id,name1,ankunft_sollvon,ankunft_sollbis,ankunft,ankunftdatum,tats_ankunft,startdatum,abfahrt,tats_abfahrt,istzeitstatus,plz,ort,strasse,geox,geoy
0,92564-14,"Hesse, Sven-Erik",H/42374,553624,Greif Packaging Germany GmbH,NaN,NaN,02.03.2026 06:00,02.03.2026 09:23,02.03.2026 06:59,02.03.2026 06:00,02.03.2026 06:00,02.03.2026 06:59,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
7,92564-8,"Szmajdewicz, Marcin",H/42375,553620,Hoyer Mineraloelwerk GmbH,NaN,NaN,02.03.2026 08:10,02.03.2026 15:42,02.03.2026 13:59,02.03.2026 06:00,02.03.2026 08:40,02.03.2026 13:59,10,27374.0,Visselhoevede,Rudolf-Diesel-Str. 1,9.59857,52.98058
8,92564-8,"Szmajdewicz, Marcin",H/42375,553651,Greif Packaging Germany GmbH,NaN,NaN,02.03.2026 10:20,02.03.2026 15:42,02.03.2026 13:59,02.03.2026 06:00,02.03.2026 10:50,02.03.2026 13:59,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
9,92564-8,"Szmajdewicz, Marcin",H/42375,553652,Castrol Germany Gmbh,NaN,NaN,02.03.2026 11:01,02.03.2026 15:42,02.03.2026 14:02,02.03.2026 06:00,02.03.2026 11:31,02.03.2026 14:02,10,21107.0,Hamburg,Neuhoefer Brueckenstr. 81,9.95681,53.51455
12,92564-8,"Szmajdewicz, Marcin",H/42375,553616,Greif Packaging Germany GmbH,NaN,NaN,02.03.2026 15:42,02.03.2026 15:42,02.03.2026 18:45,02.03.2026 06:00,02.03.2026 15:42,02.03.2026 14:49,9,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2791,92564-15,"Sowa, Mariusz",H/42754,558047,Hywax GmbH,29.12.1899,29.12.1899,07.04.2026 07:51,07.04.2026 09:42,07.04.2026 09:14,07.04.2026 06:00,07.04.2026 08:21,07.04.2026 09:24,10,20457.0,Hamburg,Worthdamm 13-27,9.98213,53.53497
2795,92560-2,"Teme, Abdoulaye",H/42758,557896,Greif Packaging Germany GmbH,NaN,NaN,07.04.2026 06:00,07.04.2026 11:52,07.04.2026 06:16,07.04.2026 06:00,07.04.2026 06:00,07.04.2026 06:16,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
2796,92560-2,"Teme, Abdoulaye",H/42758,557897,Lubrizol Deutschland GmbH,07.04.2026,07.04.2026 23:59,07.04.2026 06:57,07.04.2026 11:52,07.04.2026 07:32,07.04.2026 06:00,07.04.2026 07:27,07.04.2026 09:26,10,22113.0,Hamburg,Billbrookdeich 157,10.09782,53.53610
2797,92560-2,"Teme, Abdoulaye",H/42758,557899,Greif Packaging Germany GmbH,29.12.1899,29.12.1899,07.04.2026 07:53,07.04.2026 11:52,07.04.2026 10:13,07.04.2026 06:00,07.04.2026 08:23,07.04.2026 10:41,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
2799,92560-2,"Teme, Abdoulaye",H/42758,557898,Greif Packaging Germany GmbH,NaN,NaN,07.04.2026 11:52,07.04.2026 11:52,07.04.2026 10:42,07.04.2026 06:00,07.04.2026 11:52,07.04.2026 11:33,10,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348

# Zusammenfassung über die Dateien
* CIS-Daten.xlsx liefert für konsistente Daten nur die Spalten `ANKUNFT` und `ABFAHRT`, was wahrscheinlich der Soll-Zustand ist und fast konsistente Daten in `TATS_ANKUNFT` und `TATS_ABFAHRT` (152/2800 Zeilen nicht konsistent), was wahrscheinlich der Ist-Zustand ist
* Aufträge.xlsx und AufträgeOhneDisposoll.xlsx liefern kein Ankunft oder Abfahrt, sondern `Ladedatum` in vielen Spalten 
* die ganzen einzelnen hinterlegten xml Dateien für den März liefern zwar Zeitstempel, aber keine Information über Abfahrt und Ankunft -> genauso bei den Daten in der Schnittstelle
## Löschen der 152 Zeilen der Erfassungsfehler

In [27]:
df_filtered = df_filtered[df_filtered.tats_ankunft <= df_filtered.tats_abfahrt]
print(df_filtered.shape)

(2648, 19)

In [28]:
df_filtered = df_filtered.drop(columns=['ankunft_sollvon', 'ankunft_sollbis', 'ankunftdatum', 'startdatum', 'istzeitstatus'])

### Datentyp object für Ankunft und Abfahrt in dataetime umwandeln

In [29]:
df_filtered.dtypes

lkwnr              object
fahrername         object
tournr             object
tourstation_id      int64
name1              object
ankunft            object
tats_ankunft       object
abfahrt            object
tats_abfahrt       object
plz               float64
ort                object
strasse            object
geox              float64
geoy              float64
dtype: object

In [30]:
# df_filtered["ankunft_dt"] = pd.to_datetime(
#     df_filtered["ankunft"]
#       .astype(str)
#       .str.replace("\xa0", " ", regex=False)
#       .str.strip(),
#     format="%d.%m.%Y %H:%M",
#     errors="coerce"
# )
# df_filtered

In [31]:
dt_cols = ['ankunft','tats_ankunft','abfahrt','tats_abfahrt']
for col in dt_cols:
    if col in df_filtered.columns:
        df_filtered[col] = pd.to_datetime(
            df_filtered[col]
            .astype(str)
            .str.replace("\xa0", " ", regex=False)
            .str.strip(),
            format="%d.%m.%Y %H:%M",
            errors="coerce"
        )
        # Also try date-only format
        mask = df_filtered[col].isna()
        if mask.any():
            df_filtered.loc[mask, col] = pd.to_datetime(df_filtered.loc[mask, col], errors='coerce')
df_filtered

,lkwnr,fahrername,tournr,tourstation_id,name1,ankunft,tats_ankunft,abfahrt,tats_abfahrt,plz,ort,strasse,geox,geoy
0,92564-14,"Hesse, Sven-Erik",H/42374,553624,Greif Packaging Germany GmbH,2026-03-02 06:00:00,2026-03-02 06:59:00,2026-03-02 06:00:00,2026-03-02 06:59:00,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
1,92564-14,"Hesse, Sven-Erik",H/42374,553625,Greif Packaging Germany GmbH,2026-03-02 06:00:00,2026-03-02 07:00:00,2026-03-02 06:30:00,2026-03-02 09:28:00,20457.0,Hamburg,Brandenburger Straße 12,9.98632,53.52348
2,92564-14,"Hesse, Sven-Erik",H/42374,553626,Shell Deutschland GmbH,2026-03-02 06:49:00,2026-03-02 07:18:00,2026-03-02 07:19:00,2026-03-02 09:30:00,20457.0,Hamburg,Worthdamm 32 Building: Grasbrook Lubrica,9.99383,53.54751
3,92564-14,"Hesse, Sven-Erik",H/42374,553634,Greif Packaging Germany GmbH,2026-03-02 07:41:00,2026-03-02 09:56:00,2026-03-02 08:11:00,2026-03-02 16:25:00,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
4,92564-14,"Hesse, Sven-Erik",H/42374,553635,Shell Deutschland GmbH,2026-03-02 08:31:00,2026-03-02 11:16:00,2026-03-02 09:01:00,2026-03-02 17:15:00,20457.0,Hamburg,Worthdamm 32 Building: Grasbrook Lubrica,9.99383,53.54751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2795,92560-2,"Teme, Abdoulaye",H/42758,557896,Greif Packaging Germany GmbH,2026-04-07 06:00:00,2026-04-07 06:16:00,2026-04-07 06:00:00,2026-04-07 06:16:00,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
2796,92560-2,"Teme, Abdoulaye",H/42758,557897,Lubrizol Deutschland GmbH,2026-04-07 06:57:00,2026-04-07 07:32:00,2026-04-07 07:27:00,2026-04-07 09:26:00,22113.0,Hamburg,Billbrookdeich 157,10.09782,53.53610
2797,92560-2,"Teme, Abdoulaye",H/42758,557899,Greif Packaging Germany GmbH,2026-04-07 07:53:00,2026-04-07 10:13:00,2026-04-07 08:23:00,2026-04-07 10:41:00,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
2798,92560-2,"Teme, Abdoulaye",H/42758,557900,Blue Cube Germany GmbH Stade,2026-04-07 09:52:00,2026-04-07 13:47:00,2026-04-07 10:22:00,2026-04-07 15:18:00,21683.0,Stade,Buetzflethersand,9.51017,53.64711
2799,92560-2,"Teme, Abdoulaye",H/42758,557898,Greif Packaging Germany GmbH,2026-04-07 11:52:00,2026-04-07 10:42:00,2026-04-07 11:52:00,2026-04-07 11:33:00,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348

# Was ist `Tourstation_ID`?
* jede Station scheint nicht eine eindeutige ID zu haben wie vermutet, sondern das sind nur fortschreitene Zahlen -> unnötige Spalte

In [33]:
df_filtered.tourstation_id.nunique()

2587

In [34]:
df_filtered.geox.nunique()

237

In [32]:
df_filtered.dtypes

lkwnr                     object
fahrername                object
tournr                    object
tourstation_id             int64
name1                     object
ankunft           datetime64[ns]
tats_ankunft      datetime64[ns]
abfahrt           datetime64[ns]
tats_abfahrt      datetime64[ns]
plz                      float64
ort                       object
strasse                   object
geox                     float64
geoy                     float64
dtype: object

In [35]:
df_soll = df_filtered[['lkwnr',	'fahrername', 'tournr', 'name1', 'ankunft',	'abfahrt', 'plz', 'ort','strasse','geox','geoy']]
df_soll

,lkwnr,fahrername,tournr,name1,ankunft,abfahrt,plz,ort,strasse,geox,geoy
0,92564-14,"Hesse, Sven-Erik",H/42374,Greif Packaging Germany GmbH,2026-03-02 06:00:00,2026-03-02 06:00:00,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
1,92564-14,"Hesse, Sven-Erik",H/42374,Greif Packaging Germany GmbH,2026-03-02 06:00:00,2026-03-02 06:30:00,20457.0,Hamburg,Brandenburger Straße 12,9.98632,53.52348
2,92564-14,"Hesse, Sven-Erik",H/42374,Shell Deutschland GmbH,2026-03-02 06:49:00,2026-03-02 07:19:00,20457.0,Hamburg,Worthdamm 32 Building: Grasbrook Lubrica,9.99383,53.54751
3,92564-14,"Hesse, Sven-Erik",H/42374,Greif Packaging Germany GmbH,2026-03-02 07:41:00,2026-03-02 08:11:00,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
4,92564-14,"Hesse, Sven-Erik",H/42374,Shell Deutschland GmbH,2026-03-02 08:31:00,2026-03-02 09:01:00,20457.0,Hamburg,Worthdamm 32 Building: Grasbrook Lubrica,9.99383,53.54751
...,...,...,...,...,...,...,...,...,...,...,...
2795,92560-2,"Teme, Abdoulaye",H/42758,Greif Packaging Germany GmbH,2026-04-07 06:00:00,2026-04-07 06:00:00,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
2796,92560-2,"Teme, Abdoulaye",H/42758,Lubrizol Deutschland GmbH,2026-04-07 06:57:00,2026-04-07 07:27:00,22113.0,Hamburg,Billbrookdeich 157,10.09782,53.53610
2797,92560-2,"Teme, Abdoulaye",H/42758,Greif Packaging Germany GmbH,2026-04-07 07:53:00,2026-04-07 08:23:00,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348
2798,92560-2,"Teme, Abdoulaye",H/42758,Blue Cube Germany GmbH Stade,2026-04-07 09:52:00,2026-04-07 10:22:00,21683.0,Stade,Buetzflethersand,9.51017,53.64711
2799,92560-2,"Teme, Abdoulaye",H/42758,Greif Packaging Germany GmbH,2026-04-07 11:52:00,2026-04-07 11:52:00,20457.0,Hamburg,Brandenburger Str. 12,9.98632,53.52348

In [37]:
df_ist = pd.read_csv('Ist_Daten_mit_Tournummern.csv')
print(df_ist.shape)
df_ist.head()

(2875, 17)

,Fahrer PIN,Fahrername,Formularnummer,Formularbeschreibung,Meldungszeit,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Fahrzeug,DATUM,KENNZ_CLEAN,TOURNR
0,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-30 05:18:19,0,0,317003.220,0.0,0.0,"53,6677","9,99287","DE - 22419 Hamburg (Langenhorn), Essener Straß...",OD-TS 8041 - Fahrzeugdetails,2026-03-30,OD-TS8041,H/42647
1,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-30 06:17:22,0,0,317003.270,0.0,0.0,"53,66773","9,9932","DE - 22419 Hamburg (Langenhorn), Essener Straß...",OD-TS 8041 - Fahrzeugdetails,2026-03-30,OD-TS8041,H/42647
2,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-30 06:59:54,131,0,317021.295,0.0,0.0,"53,55026","9,99017","DE - 20457 Hamburg (Hamburg-Mitte), Alter Wall 32",OD-TS 8041 - Fahrzeugdetails,2026-03-30,OD-TS8041,H/42647
3,8160.0,"Jorczik, Christian",1651,Abfahrt Kunde,2026-03-30 06:59:55,128,0,317021.295,0.0,0.0,"53,55026","9,99018","DE - 20457 Hamburg (Hamburg-Mitte), Alter Wall 32",OD-TS 8041 - Fahrzeugdetails,2026-03-30,OD-TS8041,H/42647
4,8160.0,"Jorczik, Christian",1650,Ankunft Kunde,2026-03-30 07:28:23,0,0,317028.945,0.0,0.0,"53,57519","9,9127","DE - 22525 Hamburg (Bahrenfeld), Winsbergring 15",OD-TS 8041 - Fahrzeugdetails,2026-03-30,OD-TS8041,H/42647