## Analyse Fahrerverhalten

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Ist-Daten.csv', sep=',', encoding='utf-8')  # sep=',' falls Komma-getrennt

# Erste Übersicht
print(df.shape)
print(df.dtypes)
df.head()

(1499, 17)
Fahrer PIN         float64
Fahrername          object
Formularnummer       int64
Richtung             int64
Geschwindigkeit      int64
KM-Stand           float64
Gesamtverbrauch    float64
Tankfüllstand      float64
Breitengrad         object
Längengrad          object
Position            object
Fahrzeug            object
DATUM               object
KENNZ_CLEAN         object
TOURNR              object
Abfahrt             object
Ankunft             object
dtype: object

,Fahrer PIN,Fahrername,Formularnummer,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Fahrzeug,DATUM,KENNZ_CLEAN,TOURNR,Abfahrt,Ankunft
0,8160.0,"Jorczik, Christian",1650,74,0,316550.025,0.0,0.0,"53,66758","9,99266","DE - 22419 Hamburg (Langenhorn), Essener Straß...",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 07:00:13,2026-03-24 05:19:13
1,8160.0,"Jorczik, Christian",1650,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 07:34:00,2026-03-24 07:33:59
2,8160.0,"Jorczik, Christian",1650,0,0,316568.980,0.0,0.0,"53,58884","9,87736","DE - 22547 Hamburg (Lurup), Elbgaustraße (Ring...",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 07:54:22,2026-03-24 07:54:21
3,8160.0,"Jorczik, Christian",1650,117,0,316575.795,0.0,0.0,"53,55228","9,93833","DE - 22767 Hamburg (Altona-Altstadt), Große Be...",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 08:27:18,2026-03-24 08:27:17
4,8160.0,"Jorczik, Christian",1650,0,0,316582.760,0.0,0.0,"53,53633","10,01815","DE - 20457 Hamburg (Hamburg-Mitte), Kirchenpau...",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 08:54:13,2026-03-24 08:54:10

In [41]:
# Zeitstempel konvertieren
df['Abfahrt'] = pd.to_datetime(df['Abfahrt'])
df['Ankunft'] = pd.to_datetime(df['Ankunft'])

# Standzeit berechnen (nur wo beide vorhanden)
df['Standzeit_min'] = (
    df['Abfahrt'] - df['Ankunft']
).dt.total_seconds() / 60

In [42]:
df[df['Standzeit_min'] < 0]

,Fahrer PIN,Fahrername,Formularnummer,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Fahrzeug,DATUM,KENNZ_CLEAN,TOURNR,Abfahrt,Ankunft,Standzeit_min
220,8205.0,"Borrs, Thomas",1651,332,0,0.000,0.000,0.0,"53,5043","10,50661","DE - 21493 Schwarzenbek (Rülau), Röntgenstraße 27",Plö-TS853 - Fahrzeugdetails,2026-03-26,Plö-TS853,H/42619,2026-03-26 09:07:14,2026-03-26 09:07:29,-0.250000
433,8310.0,"Giewon, Mariusz",1651,0,0,179884.875,51151.004,10.4,"53,52283","9,98839","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",PI-EN 444 - Fahrzeugdetails,2026-04-02,PI-EN 444,H/42698,2026-04-02 10:09:07,2026-04-02 10:09:14,-0.116667
445,8314.0,"Teme, Abdoulaye",1651,0,0,144180.310,45962.316,40.0,"53,64449","9,49934","DE - 21683 Stade (Bützfleth), Bützflether Sand",PI-EN 900 - Fahrzeugdetails,2026-04-02,PI-EN 900,H/42673,2026-04-02 10:23:30,2026-04-02 10:47:47,-24.283333
539,8180.0,"Krüger, Alexander",1651,0,0,503600.865,0.000,0.0,"53,52258","9,98989","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",TS859 - Fahrzeugdetails,2026-03-31,Plo-TS859,H/42646,2026-03-31 09:22:26,2026-03-31 09:22:41,-0.250000
542,8180.0,"Krüger, Alexander",1651,0,0,503606.790,0.000,0.0,"53,51282","9,9689","DE - 21107 Hamburg (Hamburg-Mitte), Neuhöfer D...",TS859 - Fahrzeugdetails,2026-03-31,Plo-TS859,H/42646,2026-03-31 10:21:03,2026-03-31 10:21:25,-0.366667
593,8160.0,"Jorczik, Christian",1651,0,0,315693.335,0.000,0.0,"53,52071","10,09454","DE - 22113 Hamburg (Hamburg-Mitte), Bredowstra...",OD-TS 8041 - Fahrzeugdetails,2026-03-16,OD-TS8041,H/42511,2026-03-16 08:41:31,2026-03-16 08:41:33,-0.033333
758,8310.0,"Giewon, Mariusz",1651,0,0,179538.750,51046.824,18.0,"53,51533","9,95695","DE - 21107 Hamburg (Hamburg-Mitte), Neuhöfer B...",PI-EN 444 - Fahrzeugdetails,2026-03-20,PI-EN 444,H/42569,2026-03-20 11:39:23,2026-03-20 12:23:36,-44.216667
858,8180.0,"Krüger, Alexander",1651,0,0,503257.255,0.000,0.0,"53,52263","9,98947","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",TS859 - Fahrzeugdetails,2026-03-18,Plo-TS859,H/42537,2026-03-18 09:44:31,2026-03-18 09:44:33,-0.033333
1163,8180.0,"Krüger, Alexander",1651,0,0,502910.415,0.000,0.0,"53,52286","9,98855","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",TS859 - Fahrzeugdetails,2026-03-09,Plo-TS859,H/42448,2026-03-09 10:32:17,2026-03-09 10:57:06,-24.816667
1171,8180.0,"Krüger, Alexander",1651,0,0,502959.180,0.000,0.0,"53,52262","9,98941","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",TS859 - Fahrzeugdetails,2026-03-10,Plo-TS859,H/42459,2026-03-10 11:51:11,2026-03-10 11:51:14,-0.050000
1207,8197.0,"Hrzuska, Krzystof",1651,323,0,805964.005,0.000,0.0,"53,5226","9,98945","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",WL-PL431 - Fahrzeugdetails,2026-03-09,WL-PL431,H/42480,2026-03-09 07:46:50,2026-03-09 07:52:35,-5.750000
1414,8205.0,"Borrs, Thomas",1651,250,0,0.000,0.000,0.0,"53,57474","10,03696","DE - 22081 Hamburg (Barmbek-Süd), Holsteinisch...",Plö-TS853 - Fahrzeugdetails,2026-03-04,Plö-TS853,H/42408,2026-03-04 08:04:32,2026-03-04 08:05:04,-0.533333
1492,8180.0,"Krüger, Alexander",1651,78,3,502852.370,0.000,0.0,"53,5226","9,98913","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432,2026-03-06 11:00:07,2026-03-06 11:00:47,-0.666667

In [43]:
df['Standzeit_min'].describe()

count    731.000000
mean      11.398472
std       26.311953
min      -44.216667
25%        0.016667
50%        0.900000
75%        7.325000
max      306.783333
Name: Standzeit_min, dtype: float64

In [44]:
df['Abfahrt'].isna().sum()

np.int64(368)

In [45]:
df['Ankunft'].isna().sum()

np.int64(400)

In [46]:
df['Position'].nunique()

360

In [47]:
# Schritt 1: Originale Reihenfolge merken
df = df.reset_index(drop=True)
df['_order'] = df.index

# Schritt 2: Konsekutive Gruppe identifizieren
df['_new_block'] = (
    (df['TOURNR'] != df['TOURNR'].shift()) |
    (df['Position'] != df['Position'].shift())
).cumsum()

# Schritt 3: Innerhalb jedes Blocks zusammenführen
df_merged = (
    df.groupby(['TOURNR', 'Position', '_new_block'], as_index=False)
    .agg(
        Abfahrt=('Abfahrt', 'first'),
        Ankunft=('Ankunft', 'first'),
        Fahrername=('Fahrername', 'first'),
        KENNZ_CLEAN=('KENNZ_CLEAN', 'first'),
        Längengrad=('Längengrad', 'first'),
        Breitengrad=('Breitengrad', 'first'),
        _order=('_order', 'first'),  # kleinsten Index des Blocks merken
    )
)

# Schritt 4: Nach originalem Index sortieren, Hilfsspalten entfernen
df_merged = (
    df_merged
    .sort_values('_order')
    .drop(columns=['_new_block', '_order'])
    .reset_index(drop=True)
)

print(f"Zeilen vorher: {len(df)}")
print(f"Zeilen nachher: {len(df_merged)}")
df_merged.head(20)

Zeilen vorher: 1499
Zeilen nachher: 1306

,TOURNR,Position,Abfahrt,Ankunft,Fahrername,KENNZ_CLEAN,Längengrad,Breitengrad
0,H/42592,"DE - 22419 Hamburg (Langenhorn), Essener Straß...",2026-03-24 07:00:13,2026-03-24 05:19:13,"Jorczik, Christian",OD-TS8041,"9,99266","53,66758"
1,H/42592,"DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",2026-03-24 07:34:00,2026-03-24 07:33:59,"Jorczik, Christian",OD-TS8041,"9,91377","53,58982"
2,H/42592,"DE - 22547 Hamburg (Lurup), Elbgaustraße (Ring...",2026-03-24 07:54:22,2026-03-24 07:54:21,"Jorczik, Christian",OD-TS8041,"9,87736","53,58884"
3,H/42592,"DE - 22767 Hamburg (Altona-Altstadt), Große Be...",2026-03-24 08:27:18,2026-03-24 08:27:17,"Jorczik, Christian",OD-TS8041,"9,93833","53,55228"
4,H/42592,"DE - 20457 Hamburg (Hamburg-Mitte), Kirchenpau...",2026-03-24 08:54:13,2026-03-24 08:54:10,"Jorczik, Christian",OD-TS8041,"10,01815","53,53633"
5,H/42592,"DE - 21107 Hamburg (Hamburg-Mitte), Alter Reth...",2026-03-24 09:22:58,2026-03-24 09:22:57,"Jorczik, Christian",OD-TS8041,"9,96458","53,51012"
6,H/42592,"DE - 21029 Hamburg (Bergedorf), A 25",2026-03-24 10:32:59,2026-03-24 10:32:59,"Jorczik, Christian",OD-TS8041,"10,21601","53,47737"
7,H/42624,"DE - 22419 Hamburg (Langenhorn), Essener Straß...",2026-03-25 06:32:25,2026-03-25 04:55:09,"Jorczik, Christian",OD-TS8041,"9,99288","53,6677"
8,H/42624,"DE - 21035 Hamburg (Bergedorf), Randersweide",2026-03-25 08:29:13,2026-03-25 08:28:55,"Jorczik, Christian",OD-TS8041,"10,19488","53,47439"
9,H/42624,"DE - 21029 Hamburg (Bergedorf), A 25",2026-03-25 08:50:48,2026-03-25 08:50:47,"Jorczik, Christian",OD-TS8041,"10,21625","53,47737"
10,H/42624,"DE - 21337 Lüneburg (Neu Hagen), Kurt-Höbold-S...",2026-03-25 09:44:44,2026-03-25 09:44:43,"Jorczik, Christian",OD-TS8041,"10,48129","53,24022"
11,H/42624,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-03-25 11:49:34,2026-03-25 11:49:33,"Jorczik, Christian",OD-TS8041,"9,98603","53,52335"
12,H/42624,"DE - 24558 Henstedt-Ulzburg (Ulzburg), Tiedenk...",2026-03-25 13:07:56,2026-03-25 13:07:56,"Jorczik, Christian",OD-TS8041,"9,97611","53,80122"
13,H/42613,"DE - 22419 Hamburg (Langenhorn), Essener Straß...",2026-03-26 05:41:10,2026-03-26 05:13:21,"Jorczik, Christian",OD-TS8041,"9,99267","53,66767"
14,H/42613,"DE - 22763 Hamburg (Othmarschen), Jürgen-Töpfe...",NaT,2026-03-26 06:40:53,"Jorczik, Christian",OD-TS8041,"9,9073","53,5559"
15,H/42613,"DE - 22525 Hamburg (Eimsbüttel), Försterweg 81",2026-03-26 06:59:16,2026-03-26 06:59:15,"Jorczik, Christian",OD-TS8041,"9,9252","53,58168"
16,H/42613,"DE - 22763 Hamburg (Othmarschen), Jürgen-Töpfe...",2026-03-26 08:31:19,2026-03-26 08:30:45,"Jorczik, Christian",OD-TS8041,"9,90722","53,55662"
17,H/42613,"DE - 20097 Hamburg (Hamburg-Mitte), Frankenstr...",2026-03-26 11:06:00,2026-03-26 11:05:59,"Jorczik, Christian",OD-TS8041,"10,02374","53,54828"
18,H/42613,"DE - 22767 Hamburg (Altona-Altstadt), Große El...",2026-03-26 11:55:43,2026-03-26 11:55:42,"Jorczik, Christian",OD-TS8041,"9,94983","53,54455"
19,H/42613,"DE - 22767 Hamburg (Altona-Altstadt), Lamp'lweg 1",2026-03-26 12:08:48,2026-03-26 12:08:48,"Jorczik, Christian",OD-TS8041,"9,93835","53,55227"

In [48]:
df_merged['Ankunft'].isna().sum()

np.int64(230)

In [49]:
df_merged['Ankunft'].isna().sum()

np.int64(230)

In [50]:
df.head(30)

,Fahrer PIN,Fahrername,Formularnummer,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Fahrzeug,DATUM,KENNZ_CLEAN,TOURNR,Abfahrt,Ankunft,Standzeit_min,_order,_new_block
0,8160.0,"Jorczik, Christian",1650,74,0,316550.025,0.0,0.0,"53,66758","9,99266","DE - 22419 Hamburg (Langenhorn), Essener Straß...",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 07:00:13,2026-03-24 05:19:13,101.000000,0,1
1,8160.0,"Jorczik, Christian",1650,0,0,316565.680,0.0,0.0,"53,58982","9,91377","DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 07:34:00,2026-03-24 07:33:59,0.016667,1,2
2,8160.0,"Jorczik, Christian",1650,0,0,316568.980,0.0,0.0,"53,58884","9,87736","DE - 22547 Hamburg (Lurup), Elbgaustraße (Ring...",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 07:54:22,2026-03-24 07:54:21,0.016667,2,3
3,8160.0,"Jorczik, Christian",1650,117,0,316575.795,0.0,0.0,"53,55228","9,93833","DE - 22767 Hamburg (Altona-Altstadt), Große Be...",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 08:27:18,2026-03-24 08:27:17,0.016667,3,4
4,8160.0,"Jorczik, Christian",1650,0,0,316582.760,0.0,0.0,"53,53633","10,01815","DE - 20457 Hamburg (Hamburg-Mitte), Kirchenpau...",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 08:54:13,2026-03-24 08:54:10,0.050000,4,5
5,8160.0,"Jorczik, Christian",1650,0,0,316590.285,0.0,0.0,"53,51012","9,96458","DE - 21107 Hamburg (Hamburg-Mitte), Alter Reth...",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 09:22:58,2026-03-24 09:22:57,0.016667,5,6
6,8160.0,"Jorczik, Christian",1651,0,0,316618.695,0.0,0.0,"53,47737","10,21601","DE - 21029 Hamburg (Bergedorf), A 25",OD-TS 8041 - Fahrzeugdetails,2026-03-24,OD-TS8041,H/42592,2026-03-24 10:32:59,2026-03-24 10:32:59,0.000000,6,7
7,8160.0,"Jorczik, Christian",1650,0,0,316654.565,0.0,0.0,"53,6677","9,99288","DE - 22419 Hamburg (Langenhorn), Essener Straß...",OD-TS 8041 - Fahrzeugdetails,2026-03-25,OD-TS8041,H/42624,2026-03-25 06:32:25,2026-03-25 04:55:09,97.266667,7,8
8,8160.0,"Jorczik, Christian",1650,0,0,316696.855,0.0,0.0,"53,47439","10,19488","DE - 21035 Hamburg (Bergedorf), Randersweide",OD-TS 8041 - Fahrzeugdetails,2026-03-25,OD-TS8041,H/42624,2026-03-25 08:29:13,2026-03-25 08:28:55,0.300000,8,9
9,8160.0,"Jorczik, Christian",1650,0,0,316700.240,0.0,0.0,"53,47737","10,21625","DE - 21029 Hamburg (Bergedorf), A 25",OD-TS 8041 - Fahrzeugdetails,2026-03-25,OD-TS8041,H/42624,2026-03-25 08:50:48,2026-03-25 08:50:47,0.016667,9,10
10,8160.0,"Jorczik, Christian",1650,53,0,316745.065,0.0,0.0,"53,24022","10,48129","DE - 21337 Lüneburg (Neu Hagen), Kurt-Höbold-S...",OD-TS 8041 - Fahrzeugdetails,2026-03-25,OD-TS8041,H/42624,2026-03-25 09:44:44,2026-03-25 09:44:43,0.016667,10,11
11,8160.0,"Jorczik, Christian",1650,194,2,316803.775,0.0,0.0,"53,52335","9,98603","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",OD-TS 8041 - Fahrzeugdetails,2026-03-25,OD-TS8041,H/42624,2026-03-25 11:49:34,2026-03-25 11:49:33,0.016667,11,12
12,8160.0,"Jorczik, Christian",1651,0,0,316851.865,0.0,0.0,"53,80122","9,97611","DE - 24558 Henstedt-Ulzburg (Ulzburg), Tiedenk...",OD-TS 8041 - Fahrzeugdetails,2026-03-25,OD-TS8041,H/42624,2026-03-25 13:07:56,2026-03-25 13:07:56,0.000000,12,13
13,8160.0,"Jorczik, Christian",1650,0,0,316870.500,0.0,0.0,"53,66767","9,99267","DE - 22419 Hamburg (Langenhorn), Essener Straß...",OD-TS 8041 - Fahrzeugdetails,2026-03-26,OD-TS8041,H/42613,2026-03-26 05:41:10,2026-03-26 05:13:21,27.816667,13,14
14,8160.0,"Jorczik, Christian",1650,0,0,316888.750,0.0,0.0,"53,5559","9,9073","DE - 22763 Hamburg (Othmarschen), Jürgen-Töpfe...",OD-TS 8041 - Fahrzeugdetails,2026-03-26,OD-TS8041,H/42613,NaT,2026-03-26 06:40:53,NaN,14,15
15,8160.0,"Jorczik, Christian",1650,0,0,316896.510,0.0,0.0,"53,58168","9,9252","DE - 22525 Hamburg (Eimsbüttel), Försterweg 81",OD-TS 8041 - Fahrzeugdetails,2026-03-26,OD-TS8041,H/42613,2026-03-26 06:59:16,2026-03-26 06:59:15,0.016667,15,16
16,8160.0,"Jorczik, Christian",1650,0,0,316928.645,0.0,0.0,"53,55662","9,90722","DE - 22763 Hamburg (Othmarschen), Jürgen-Töpfe...",OD-TS 8041 - Fahrzeugdetails,2026-03-26,OD-TS8041,H/42613,2026-03-26 08:31:19,2026-03-26 08:30:45,0.566667,16,17
17,8160.0,"Jorczik, Christian",1650,0,0,316973.410,0.0,0.0,"53,54828","10,02374","DE - 20097 Hamburg (Hamburg-Mitte), Frankenstr...",OD-TS 8041 - Fahrzeugdetails,2026-03-26,OD-TS8041,H/42613,2026-03-26 11:06:00,2026-03-26 11:05:59,0.016667,17,18
18,8160.0,"Jorczik, Christian",1650,0,0,316980.335,0.0,0.0,"53,54455","9,94983","DE - 22767 Hamburg (Altona-Altstadt), Große El...",OD-TS 8041 - Fahrzeugdetails,2026-03-26,OD-TS8041,H/42613,2026-03-26 11:55:43,2026-03-26 11:55:42,0.016667,18,19
19,8160.0,"Jorczik, Christian",1651,0,0,316982.830,0.0,0.0,"53,55227","9,93835","DE - 22767 Hamburg (Altona-Altstadt), Lamp'lweg 1",OD-TS 8041 - Fahrzeugdetails,2026-03-26,OD-TS8041,H/42613,2026-03-26 12:08:48,2026-03-26 12:08:48,0.000000,19,20
20,8160.0,"Jorczik, Christian",1650,15,1,316986.795,0.0,0.0,"53,55651","9,90113","DE - 22763 Hamburg (Othmarschen), Paul-Ehrlich...",OD-TS 8041 - Fahrzeugdetails,2026-03-26,OD-TS8041,H/42613,2026-03-26 12:23:50,2026-03-26 12:23:49,0.016667,20,21
21,8168.0,"Calina, Florin Alexandru",1650,0,0,464026.075,0.0,0.0,"53,52268","9,98922","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,NaT,2026-03-23 06:19:04,NaN,21,22
22,8168.0,"Calina, Florin Alexandru",1651,0,0,464026.545,0.0,0.0,"53,52267","9,98932","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,2026-03-23 06:48:11,NaT,NaN,22,22
23,8168.0,"Calina, Florin Alexandru",1650,0,0,464105.570,0.0,0.0,"53,92437","10,32141","DE - 23795 Bad Segeberg, Asternweg 2",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,NaT,2026-03-23 08:10:20,NaN,23,23
24,8168.0,"Calina, Florin Alexandru",1651,286,2,464106.430,0.0,0.0,"53,92526","10,31985","DE - 23795 Bad Segeberg, Asternweg 2",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,2026-03-23 08:59:41,NaT,NaN,24,23
25,8168.0,"Calina, Florin Alexandru",1650,0,0,464177.000,0.0,0.0,"53,52288","9,98856","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,2026-03-23 11:31:24,2026-03-23 11:31:22,0.033333,25,24
26,8168.0,"Calina, Florin Alexandru",1650,0,0,464230.765,0.0,0.0,"53,63087","9,50849","DE - 21683 Stade, Stader Elbstraße",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,NaT,2026-03-23 12:40:10,NaN,26,25
27,8168.0,"Calina, Florin Alexandru",1651,166,1,464233.290,0.0,0.0,"53,62125","9,50019","DE - 21683 Stade, Stader Elbstraße",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,2026-03-23 14:11:16,NaT,NaN,27,25
28,8168.0,"Calina, Florin Alexandru",1650,0,0,464406.495,0.0,0.0,"53,52332","9,98586","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",OD-TS 8046 - Fahrzeugdetails,2026-03-26,OD-TS8046,H/42601,2026-03-26 15:27:13,2026-03-26 15:27:04,0.150000,28,26
29,8258.0,"Oelschlaeger, Marcel",1650,105,0,196469.105,0.0,0.0,"53,66759","9,99216","DE - 22419 Hamburg (Langenhorn), Essener Straß...",OD-TS 8048 - Fahrzeugdetails,2026-03-23,OD-TS8048,H/42579,2026-03-23 06:16:55,2026-03-23 05:03:08,73.783333,29,27

In [51]:
df_merged[df_merged['TOURNR'] == 'H/42578']

,TOURNR,Position,Abfahrt,Ankunft,Fahrername,KENNZ_CLEAN,Längengrad,Breitengrad
21,H/42578,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-03-23 06:48:11,2026-03-23 06:19:04,"Calina, Florin Alexandru",OD-TS8046,"9,98922","53,52268"
22,H/42578,"DE - 23795 Bad Segeberg, Asternweg 2",2026-03-23 08:59:41,2026-03-23 08:10:20,"Calina, Florin Alexandru",OD-TS8046,"10,32141","53,92437"
23,H/42578,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-03-23 11:31:24,2026-03-23 11:31:22,"Calina, Florin Alexandru",OD-TS8046,"9,98856","53,52288"
24,H/42578,"DE - 21683 Stade, Stader Elbstraße",2026-03-23 14:11:16,2026-03-23 12:40:10,"Calina, Florin Alexandru",OD-TS8046,"9,50849","53,63087"

In [52]:
df[df['TOURNR'] == 'H/42578']

,Fahrer PIN,Fahrername,Formularnummer,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Fahrzeug,DATUM,KENNZ_CLEAN,TOURNR,Abfahrt,Ankunft,Standzeit_min,_order,_new_block
21,8168.0,"Calina, Florin Alexandru",1650,0,0,464026.075,0.0,0.0,"53,52268","9,98922","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,NaT,2026-03-23 06:19:04,NaN,21,22
22,8168.0,"Calina, Florin Alexandru",1651,0,0,464026.545,0.0,0.0,"53,52267","9,98932","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,2026-03-23 06:48:11,NaT,NaN,22,22
23,8168.0,"Calina, Florin Alexandru",1650,0,0,464105.570,0.0,0.0,"53,92437","10,32141","DE - 23795 Bad Segeberg, Asternweg 2",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,NaT,2026-03-23 08:10:20,NaN,23,23
24,8168.0,"Calina, Florin Alexandru",1651,286,2,464106.430,0.0,0.0,"53,92526","10,31985","DE - 23795 Bad Segeberg, Asternweg 2",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,2026-03-23 08:59:41,NaT,NaN,24,23
25,8168.0,"Calina, Florin Alexandru",1650,0,0,464177.000,0.0,0.0,"53,52288","9,98856","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,2026-03-23 11:31:24,2026-03-23 11:31:22,0.033333,25,24
26,8168.0,"Calina, Florin Alexandru",1650,0,0,464230.765,0.0,0.0,"53,63087","9,50849","DE - 21683 Stade, Stader Elbstraße",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,NaT,2026-03-23 12:40:10,NaN,26,25
27,8168.0,"Calina, Florin Alexandru",1651,166,1,464233.290,0.0,0.0,"53,62125","9,50019","DE - 21683 Stade, Stader Elbstraße",OD-TS 8046 - Fahrzeugdetails,2026-03-23,OD-TS8046,H/42578,2026-03-23 14:11:16,NaT,NaN,27,25

In [53]:
# Tournummern bei denen Abfahrt ODER Ankunft noch NaN ist
tournr_mit_nan = (
    df_merged[df_merged['Abfahrt'].isna() | df_merged['Ankunft'].isna()]
    ['TOURNR']
    .unique()
)

print(f"Anzahl betroffener Tournummern: {len(tournr_mit_nan)}")
print(tournr_mit_nan)

Anzahl betroffener Tournummern: 140
['H/42613' 'H/42579' 'H/42596' 'H/42612' 'H/42573' 'H/42606' 'H/42607'
 'H/42608' 'H/42581' 'H/42631' 'H/42632' 'H/42600' 'H/42616' 'H/42620'
 'H/42577' 'H/42594' 'H/42618' 'H/42619' 'H/42572' 'H/42589' 'H/42603'
 'H/42604' 'H/42605' 'H/42574' 'H/42591' 'H/42609' 'H/42610' 'H/42647'
 'H/42650' 'H/42712' 'H/42662' 'H/42681' 'H/42656' 'H/42708' 'H/42677'
 'H/42653' 'H/42664' 'H/42709' 'H/42698' 'H/42673' 'H/42684' 'H/42685'
 'H/42649' 'H/42660' 'H/42687' 'H/42644' 'H/42655' 'H/42710' 'H/42675'
 'H/42646' 'H/42711' 'H/42679' 'H/42652' 'H/42663' 'H/42511' 'H/42528'
 'H/42514' 'H/42554' 'H/42566' 'H/42555' 'H/42509' 'H/42525' 'H/42517'
 'H/42532' 'H/42545' 'H/42557' 'H/42569' 'H/42507' 'H/42523' 'H/42513'
 'H/42529' 'H/42540' 'H/42565' 'H/42508' 'H/42524' 'H/42535' 'H/42548'
 'H/42560' 'H/42510' 'H/42537' 'H/42550' 'H/42562' 'H/42544' 'H/42556'
 'H/42568' 'H/42460' 'H/42472' 'H/42463' 'H/42475' 'H/42476' 'H/42505'
 'H/42506' 'H/42455' 'H/42466' 'H/42478' 'H/42504' 'H/42445' 'H/42456'
 'H/42468' 'H/42450' 'H/42474' 'H/42488' 'H/42500' 'H/42446' 'H/42457'
 'H/42469' 'H/42483' 'H/42495' 'H/42448' 'H/42459' 'H/42471' 'H/42485'
 'H/42480' 'H/42481' 'H/42484' 'H/42491' 'H/42407' 'H/42380' 'H/42397'
 'H/42424' 'H/42381' 'H/42375' 'H/42392' 'H/42404' 'H/42419' 'H/42431'
 'H/42379' 'H/42396' 'H/42408' 'H/42423' 'H/42435' 'H/42374' 'H/42391'
 'H/42403' 'H/42418' 'H/42430' 'H/42376' 'H/42393' 'H/42405' 'H/42432']

In [54]:
df[df['TOURNR'] == 'H/42379']

,Fahrer PIN,Fahrername,Formularnummer,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Fahrzeug,DATUM,KENNZ_CLEAN,TOURNR,Abfahrt,Ankunft,Standzeit_min,_order,_new_block
1388,8205.0,"Borrs, Thomas",1650,201,0,0.0,0.0,0.0,"53,64615","10,03509","DE - 22339 Hamburg (Hummelsbüttel), Lademannbo...",Plö-TS853 - Fahrzeugdetails,2026-03-02,Plö-TS853,H/42379,2026-03-02 06:43:12,2026-03-02 06:41:10,2.033333,1388,1208
1389,8205.0,"Borrs, Thomas",1650,243,0,0.0,0.0,0.0,"53,67178","10,23988","DE - 22926 Ahrensburg, Manhagener Allee 10",Plö-TS853 - Fahrzeugdetails,2026-03-02,Plö-TS853,H/42379,NaT,2026-03-02 07:15:59,NaN,1389,1209
1390,8205.0,"Borrs, Thomas",1651,68,0,0.0,0.0,0.0,"53,67134","10,24056","DE - 22926 Ahrensburg, Heinz-Beusen-Stieg",Plö-TS853 - Fahrzeugdetails,2026-03-02,Plö-TS853,H/42379,2026-03-02 07:21:33,NaT,NaN,1390,1210
1391,8205.0,"Borrs, Thomas",1650,127,0,0.0,0.0,0.0,"53,61838","10,23141","DE - 22145 Braak, Waldweg 2",Plö-TS853 - Fahrzeugdetails,2026-03-02,Plö-TS853,H/42379,2026-03-02 08:07:02,2026-03-02 07:36:37,30.416667,1391,1211
1392,8205.0,"Borrs, Thomas",1650,96,0,0.0,0.0,0.0,"53,52827","10,2351","DE - 21465 Reinbek, Humboldtstraße 1",Plö-TS853 - Fahrzeugdetails,2026-03-02,Plö-TS853,H/42379,2026-03-02 08:26:23,2026-03-02 08:24:45,1.633333,1392,1212
1393,8205.0,"Borrs, Thomas",1650,229,0,0.0,0.0,0.0,"53,59222","10,0374","DE - 22307 Hamburg (Barmbek-Nord), Weg 1",Plö-TS853 - Fahrzeugdetails,2026-03-02,Plö-TS853,H/42379,NaT,2026-03-02 09:16:15,NaN,1393,1213
1394,8205.0,"Borrs, Thomas",1651,176,0,0.0,0.0,0.0,"53,59137","10,03768","DE - 22305 Hamburg (Barmbek-Nord), Hellbrookst...",Plö-TS853 - Fahrzeugdetails,2026-03-02,Plö-TS853,H/42379,2026-03-02 09:18:35,NaT,NaN,1394,1214
1395,8205.0,"Borrs, Thomas",1650,256,0,0.0,0.0,0.0,"53,57506","10,03912","DE - 22081 Hamburg (Barmbek-Süd), Holsteinisch...",Plö-TS853 - Fahrzeugdetails,2026-03-02,Plö-TS853,H/42379,2026-03-02 10:56:36,2026-03-02 10:54:15,2.350000,1395,1215

In [55]:
df_merged[df_merged['TOURNR'] == 'H/42379']

,TOURNR,Position,Abfahrt,Ankunft,Fahrername,KENNZ_CLEAN,Längengrad,Breitengrad
1207,H/42379,"DE - 22339 Hamburg (Hummelsbüttel), Lademannbo...",2026-03-02 06:43:12,2026-03-02 06:41:10,"Borrs, Thomas",Plö-TS853,"10,03509","53,64615"
1208,H/42379,"DE - 22926 Ahrensburg, Manhagener Allee 10",NaT,2026-03-02 07:15:59,"Borrs, Thomas",Plö-TS853,"10,23988","53,67178"
1209,H/42379,"DE - 22926 Ahrensburg, Heinz-Beusen-Stieg",2026-03-02 07:21:33,NaT,"Borrs, Thomas",Plö-TS853,"10,24056","53,67134"
1210,H/42379,"DE - 22145 Braak, Waldweg 2",2026-03-02 08:07:02,2026-03-02 07:36:37,"Borrs, Thomas",Plö-TS853,"10,23141","53,61838"
1211,H/42379,"DE - 21465 Reinbek, Humboldtstraße 1",2026-03-02 08:26:23,2026-03-02 08:24:45,"Borrs, Thomas",Plö-TS853,"10,2351","53,52827"
1212,H/42379,"DE - 22307 Hamburg (Barmbek-Nord), Weg 1",NaT,2026-03-02 09:16:15,"Borrs, Thomas",Plö-TS853,"10,0374","53,59222"
1213,H/42379,"DE - 22305 Hamburg (Barmbek-Nord), Hellbrookst...",2026-03-02 09:18:35,NaT,"Borrs, Thomas",Plö-TS853,"10,03768","53,59137"
1214,H/42379,"DE - 22081 Hamburg (Barmbek-Süd), Holsteinisch...",2026-03-02 10:56:36,2026-03-02 10:54:15,"Borrs, Thomas",Plö-TS853,"10,03912","53,57506"

In [56]:
df_merged.head(20)

,TOURNR,Position,Abfahrt,Ankunft,Fahrername,KENNZ_CLEAN,Längengrad,Breitengrad
0,H/42592,"DE - 22419 Hamburg (Langenhorn), Essener Straß...",2026-03-24 07:00:13,2026-03-24 05:19:13,"Jorczik, Christian",OD-TS8041,"9,99266","53,66758"
1,H/42592,"DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",2026-03-24 07:34:00,2026-03-24 07:33:59,"Jorczik, Christian",OD-TS8041,"9,91377","53,58982"
2,H/42592,"DE - 22547 Hamburg (Lurup), Elbgaustraße (Ring...",2026-03-24 07:54:22,2026-03-24 07:54:21,"Jorczik, Christian",OD-TS8041,"9,87736","53,58884"
3,H/42592,"DE - 22767 Hamburg (Altona-Altstadt), Große Be...",2026-03-24 08:27:18,2026-03-24 08:27:17,"Jorczik, Christian",OD-TS8041,"9,93833","53,55228"
4,H/42592,"DE - 20457 Hamburg (Hamburg-Mitte), Kirchenpau...",2026-03-24 08:54:13,2026-03-24 08:54:10,"Jorczik, Christian",OD-TS8041,"10,01815","53,53633"
5,H/42592,"DE - 21107 Hamburg (Hamburg-Mitte), Alter Reth...",2026-03-24 09:22:58,2026-03-24 09:22:57,"Jorczik, Christian",OD-TS8041,"9,96458","53,51012"
6,H/42592,"DE - 21029 Hamburg (Bergedorf), A 25",2026-03-24 10:32:59,2026-03-24 10:32:59,"Jorczik, Christian",OD-TS8041,"10,21601","53,47737"
7,H/42624,"DE - 22419 Hamburg (Langenhorn), Essener Straß...",2026-03-25 06:32:25,2026-03-25 04:55:09,"Jorczik, Christian",OD-TS8041,"9,99288","53,6677"
8,H/42624,"DE - 21035 Hamburg (Bergedorf), Randersweide",2026-03-25 08:29:13,2026-03-25 08:28:55,"Jorczik, Christian",OD-TS8041,"10,19488","53,47439"
9,H/42624,"DE - 21029 Hamburg (Bergedorf), A 25",2026-03-25 08:50:48,2026-03-25 08:50:47,"Jorczik, Christian",OD-TS8041,"10,21625","53,47737"
10,H/42624,"DE - 21337 Lüneburg (Neu Hagen), Kurt-Höbold-S...",2026-03-25 09:44:44,2026-03-25 09:44:43,"Jorczik, Christian",OD-TS8041,"10,48129","53,24022"
11,H/42624,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-03-25 11:49:34,2026-03-25 11:49:33,"Jorczik, Christian",OD-TS8041,"9,98603","53,52335"
12,H/42624,"DE - 24558 Henstedt-Ulzburg (Ulzburg), Tiedenk...",2026-03-25 13:07:56,2026-03-25 13:07:56,"Jorczik, Christian",OD-TS8041,"9,97611","53,80122"
13,H/42613,"DE - 22419 Hamburg (Langenhorn), Essener Straß...",2026-03-26 05:41:10,2026-03-26 05:13:21,"Jorczik, Christian",OD-TS8041,"9,99267","53,66767"
14,H/42613,"DE - 22763 Hamburg (Othmarschen), Jürgen-Töpfe...",NaT,2026-03-26 06:40:53,"Jorczik, Christian",OD-TS8041,"9,9073","53,5559"
15,H/42613,"DE - 22525 Hamburg (Eimsbüttel), Försterweg 81",2026-03-26 06:59:16,2026-03-26 06:59:15,"Jorczik, Christian",OD-TS8041,"9,9252","53,58168"
16,H/42613,"DE - 22763 Hamburg (Othmarschen), Jürgen-Töpfe...",2026-03-26 08:31:19,2026-03-26 08:30:45,"Jorczik, Christian",OD-TS8041,"9,90722","53,55662"
17,H/42613,"DE - 20097 Hamburg (Hamburg-Mitte), Frankenstr...",2026-03-26 11:06:00,2026-03-26 11:05:59,"Jorczik, Christian",OD-TS8041,"10,02374","53,54828"
18,H/42613,"DE - 22767 Hamburg (Altona-Altstadt), Große El...",2026-03-26 11:55:43,2026-03-26 11:55:42,"Jorczik, Christian",OD-TS8041,"9,94983","53,54455"
19,H/42613,"DE - 22767 Hamburg (Altona-Altstadt), Lamp'lweg 1",2026-03-26 12:08:48,2026-03-26 12:08:48,"Jorczik, Christian",OD-TS8041,"9,93835","53,55227"

In [57]:
# Index sicherstellen
df_merged = df_merged.reset_index(drop=True)

# Koordinaten konvertieren
if df_merged['Breitengrad'].dtype == object:
    df_merged['Breitengrad'] = df_merged['Breitengrad'].astype(str).str.replace(',', '.').astype(float)
    df_merged['Längengrad'] = df_merged['Längengrad'].astype(str).str.replace(',', '.').astype(float)

RADIUS = 1000

# Haversine
lat1 = np.radians(df_merged['Breitengrad'])
lon1 = np.radians(df_merged['Längengrad'])
lat2 = np.radians(df_merged['Breitengrad'].shift())
lon2 = np.radians(df_merged['Längengrad'].shift())

dlat = lat1 - lat2
dlon = lon1 - lon2

a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
df_merged['_dist'] = 6371000 * 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

# NUR Vorgänger-Bedingung: eine hat Ankunft=NaN, direkt vorherige hat Abfahrt=NaN (oder umgekehrt)
merge_erlaubt = (
    (df_merged['Ankunft'].isna() & df_merged['Abfahrt'].shift().isna()) |
    (df_merged['Abfahrt'].isna() & df_merged['Ankunft'].shift().isna())
)

print("merge_erlaubt True:", merge_erlaubt.sum())  # sollte jetzt 204 sein

df_merged['_new_block'] = (
    (df_merged['TOURNR'] != df_merged['TOURNR'].shift()) |
    (df_merged['_dist'] > RADIUS) |
    ~merge_erlaubt
).cumsum()

df_merged['_order'] = df_merged.index

df_merged2 = (
    df_merged.groupby(['TOURNR', '_new_block'], as_index=False)
    .agg(
        Position=('Position', 'first'),
        Abfahrt=('Abfahrt', 'first'),
        Ankunft=('Ankunft', 'last'),
        Fahrername=('Fahrername', 'first'),
        KENNZ_CLEAN=('KENNZ_CLEAN', 'first'),
        Längengrad=('Längengrad', 'first'),
        Breitengrad=('Breitengrad', 'first'),
        _order=('_order', 'first'),
    )
)

df_merged2 = (
    df_merged2
    .sort_values('_order')
    .drop(columns=['_new_block', '_order', '_dist'], errors='ignore')
    .reset_index(drop=True)
)

print(f"Zeilen zu beginn: {len(df)}")
print(f"Zeilen nach Pass 1 (Position): {len(df_merged)}")
print(f"Zeilen nach Pass 2 (Geofencing): {len(df_merged2)}")
df_merged2.head(10)

merge_erlaubt True: 204
Zeilen zu beginn: 1499
Zeilen nach Pass 1 (Position): 1306
Zeilen nach Pass 2 (Geofencing): 1171

,TOURNR,Position,Abfahrt,Ankunft,Fahrername,KENNZ_CLEAN,Längengrad,Breitengrad
0,H/42592,"DE - 22419 Hamburg (Langenhorn), Essener Straß...",2026-03-24 07:00:13,2026-03-24 05:19:13,"Jorczik, Christian",OD-TS8041,9.99266,53.66758
1,H/42592,"DE - 22525 Hamburg (Eimsbüttel), Lederstraße 3...",2026-03-24 07:34:00,2026-03-24 07:33:59,"Jorczik, Christian",OD-TS8041,9.91377,53.58982
2,H/42592,"DE - 22547 Hamburg (Lurup), Elbgaustraße (Ring...",2026-03-24 07:54:22,2026-03-24 07:54:21,"Jorczik, Christian",OD-TS8041,9.87736,53.58884
3,H/42592,"DE - 22767 Hamburg (Altona-Altstadt), Große Be...",2026-03-24 08:27:18,2026-03-24 08:27:17,"Jorczik, Christian",OD-TS8041,9.93833,53.55228
4,H/42592,"DE - 20457 Hamburg (Hamburg-Mitte), Kirchenpau...",2026-03-24 08:54:13,2026-03-24 08:54:10,"Jorczik, Christian",OD-TS8041,10.01815,53.53633
5,H/42592,"DE - 21107 Hamburg (Hamburg-Mitte), Alter Reth...",2026-03-24 09:22:58,2026-03-24 09:22:57,"Jorczik, Christian",OD-TS8041,9.96458,53.51012
6,H/42592,"DE - 21029 Hamburg (Bergedorf), A 25",2026-03-24 10:32:59,2026-03-24 10:32:59,"Jorczik, Christian",OD-TS8041,10.21601,53.47737
7,H/42624,"DE - 22419 Hamburg (Langenhorn), Essener Straß...",2026-03-25 06:32:25,2026-03-25 04:55:09,"Jorczik, Christian",OD-TS8041,9.99288,53.66770
8,H/42624,"DE - 21035 Hamburg (Bergedorf), Randersweide",2026-03-25 08:29:13,2026-03-25 08:28:55,"Jorczik, Christian",OD-TS8041,10.19488,53.47439
9,H/42624,"DE - 21029 Hamburg (Bergedorf), A 25",2026-03-25 08:50:48,2026-03-25 08:50:47,"Jorczik, Christian",OD-TS8041,10.21625,53.47737

In [58]:
#df_merged2.to_csv('Ist_Daten_nach_Geo.csv', index=False)

In [59]:
# Tournummern bei denen Abfahrt ODER Ankunft noch NaN ist
tournr_mit_nan = (
    df_merged2[df_merged2['Abfahrt'].isna() | df_merged2['Ankunft'].isna()]
    ['TOURNR']
    .unique()
)

print(f"Anzahl betroffener Tournummern: {len(tournr_mit_nan)}")
print(tournr_mit_nan)

Anzahl betroffener Tournummern: 79
['H/42613' 'H/42579' 'H/42612' 'H/42608' 'H/42616' 'H/42619' 'H/42572'
 'H/42589' 'H/42603' 'H/42604' 'H/42605' 'H/42610' 'H/42647' 'H/42709'
 'H/42698' 'H/42673' 'H/42684' 'H/42685' 'H/42644' 'H/42655' 'H/42710'
 'H/42675' 'H/42646' 'H/42711' 'H/42679' 'H/42663' 'H/42511' 'H/42514'
 'H/42554' 'H/42566' 'H/42555' 'H/42509' 'H/42525' 'H/42532' 'H/42513'
 'H/42529' 'H/42565' 'H/42508' 'H/42524' 'H/42548' 'H/42560' 'H/42510'
 'H/42537' 'H/42550' 'H/42556' 'H/42463' 'H/42505' 'H/42506' 'H/42504'
 'H/42445' 'H/42456' 'H/42468' 'H/42488' 'H/42446' 'H/42457' 'H/42469'
 'H/42483' 'H/42495' 'H/42448' 'H/42459' 'H/42471' 'H/42480' 'H/42481'
 'H/42491' 'H/42380' 'H/42397' 'H/42424' 'H/42381' 'H/42375' 'H/42419'
 'H/42408' 'H/42435' 'H/42374' 'H/42391' 'H/42403' 'H/42418' 'H/42430'
 'H/42393' 'H/42432']

In [60]:
df_merged2['Ankunft'].isna().sum()

np.int64(95)

In [61]:
df_merged2['Abfahrt'].isna().sum()

np.int64(61)

In [62]:
df_merged2['Abfahrt'] = pd.to_datetime(df_merged2['Abfahrt'])
df_merged2['Ankunft'] = pd.to_datetime(df_merged2['Ankunft'])
df_merged2['Standzeit_min'] = (df_merged2['Abfahrt'] - df_merged2['Ankunft']).dt.total_seconds() / 60

In [63]:
df_merged2['Standzeit_min'].describe()

count    1015.000000
mean       22.832627
std        38.230219
min       -82.650000
25%         0.050000
50%         4.233333
75%        32.458333
max       364.650000
Name: Standzeit_min, dtype: float64

In [64]:
df['Standzeit_min'].describe()

count    731.000000
mean      11.398472
std       26.311953
min      -44.216667
25%        0.016667
50%        0.900000
75%        7.325000
max      306.783333
Name: Standzeit_min, dtype: float64

In [65]:
df_merged2[df_merged2['Standzeit_min'] < 0]

,TOURNR,Position,Abfahrt,Ankunft,Fahrername,KENNZ_CLEAN,Längengrad,Breitengrad,Standzeit_min
163,H/42619,"DE - 21493 Schwarzenbek (Rülau), Röntgenstraße 27",2026-03-26 09:07:14,2026-03-26 09:07:29,"Borrs, Thomas",Plö-TS853,10.50661,53.50430,-0.250000
209,H/42628,"DE - 21683 Stade,",2026-03-26 09:45:56,2026-03-26 09:46:16,"Calina, Florin Alexandru",WL-PL431,9.49980,53.62354,-0.333333
324,H/42698,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-04-02 10:09:07,2026-04-02 10:09:14,"Giewon, Mariusz",PI-EN 444,9.98839,53.52283,-0.116667
332,H/42673,"DE - 21683 Stade (Bützfleth), Bützflether Sand",2026-04-02 10:23:30,2026-04-02 10:47:47,"Teme, Abdoulaye",PI-EN 900,9.49934,53.64449,-24.283333
411,H/42646,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-03-31 09:22:26,2026-03-31 09:22:41,"Krüger, Alexander",Plo-TS859,9.98989,53.52258,-0.250000
413,H/42646,"DE - 21107 Hamburg (Hamburg-Mitte), Neuhöfer D...",2026-03-31 10:21:03,2026-03-31 10:21:25,"Krüger, Alexander",Plo-TS859,9.96890,53.51282,-0.366667
663,H/42537,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-03-18 09:44:31,2026-03-18 09:44:33,"Krüger, Alexander",Plo-TS859,9.98947,53.52263,-0.033333
904,H/42448,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-03-09 10:32:17,2026-03-09 10:57:06,"Krüger, Alexander",Plo-TS859,9.98855,53.52286,-24.816667
911,H/42459,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-03-10 11:51:11,2026-03-10 11:51:14,"Krüger, Alexander",Plo-TS859,9.98941,53.52262,-0.050000
938,H/42480,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-03-09 07:46:50,2026-03-09 07:52:35,"Hrzuska, Krzystof",WL-PL431,9.98945,53.52260,-5.750000
1080,H/42419,"DE - 20457 Hamburg (Hamburg-Mitte), Worthdamm 36",2026-03-05 06:45:42,2026-03-05 08:08:21,"Szmajdewicz, Marcin",OD-TS8050,9.98225,53.53412,-82.650000
1109,H/42408,"DE - 22081 Hamburg (Barmbek-Süd), Holsteinisch...",2026-03-04 08:04:32,2026-03-04 08:05:04,"Borrs, Thomas",Plö-TS853,10.03696,53.57474,-0.533333
1161,H/42432,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-03-06 07:42:05,2026-03-06 08:13:56,"Krüger, Alexander",Plo-TS859,9.98910,53.52274,-31.850000
1165,H/42432,"DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",2026-03-06 11:00:07,2026-03-06 11:00:47,"Krüger, Alexander",Plo-TS859,9.98913,53.52260,-0.666667

In [66]:
df[df['Standzeit_min'] < 0]

,Fahrer PIN,Fahrername,Formularnummer,Richtung,Geschwindigkeit,KM-Stand,Gesamtverbrauch,Tankfüllstand,Breitengrad,Längengrad,Position,Fahrzeug,DATUM,KENNZ_CLEAN,TOURNR,Abfahrt,Ankunft,Standzeit_min,_order,_new_block
220,8205.0,"Borrs, Thomas",1651,332,0,0.000,0.000,0.0,"53,5043","10,50661","DE - 21493 Schwarzenbek (Rülau), Röntgenstraße 27",Plö-TS853 - Fahrzeugdetails,2026-03-26,Plö-TS853,H/42619,2026-03-26 09:07:14,2026-03-26 09:07:29,-0.250000,220,185
433,8310.0,"Giewon, Mariusz",1651,0,0,179884.875,51151.004,10.4,"53,52283","9,98839","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",PI-EN 444 - Fahrzeugdetails,2026-04-02,PI-EN 444,H/42698,2026-04-02 10:09:07,2026-04-02 10:09:14,-0.116667,433,363
445,8314.0,"Teme, Abdoulaye",1651,0,0,144180.310,45962.316,40.0,"53,64449","9,49934","DE - 21683 Stade (Bützfleth), Bützflether Sand",PI-EN 900 - Fahrzeugdetails,2026-04-02,PI-EN 900,H/42673,2026-04-02 10:23:30,2026-04-02 10:47:47,-24.283333,445,373
539,8180.0,"Krüger, Alexander",1651,0,0,503600.865,0.000,0.0,"53,52258","9,98989","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",TS859 - Fahrzeugdetails,2026-03-31,Plo-TS859,H/42646,2026-03-31 09:22:26,2026-03-31 09:22:41,-0.250000,539,458
542,8180.0,"Krüger, Alexander",1651,0,0,503606.790,0.000,0.0,"53,51282","9,9689","DE - 21107 Hamburg (Hamburg-Mitte), Neuhöfer D...",TS859 - Fahrzeugdetails,2026-03-31,Plo-TS859,H/42646,2026-03-31 10:21:03,2026-03-31 10:21:25,-0.366667,542,460
593,8160.0,"Jorczik, Christian",1651,0,0,315693.335,0.000,0.0,"53,52071","10,09454","DE - 22113 Hamburg (Hamburg-Mitte), Bredowstra...",OD-TS 8041 - Fahrzeugdetails,2026-03-16,OD-TS8041,H/42511,2026-03-16 08:41:31,2026-03-16 08:41:33,-0.033333,593,503
758,8310.0,"Giewon, Mariusz",1651,0,0,179538.750,51046.824,18.0,"53,51533","9,95695","DE - 21107 Hamburg (Hamburg-Mitte), Neuhöfer B...",PI-EN 444 - Fahrzeugdetails,2026-03-20,PI-EN 444,H/42569,2026-03-20 11:39:23,2026-03-20 12:23:36,-44.216667,758,648
858,8180.0,"Krüger, Alexander",1651,0,0,503257.255,0.000,0.0,"53,52263","9,98947","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",TS859 - Fahrzeugdetails,2026-03-18,Plo-TS859,H/42537,2026-03-18 09:44:31,2026-03-18 09:44:33,-0.033333,858,739
1163,8180.0,"Krüger, Alexander",1651,0,0,502910.415,0.000,0.0,"53,52286","9,98855","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",TS859 - Fahrzeugdetails,2026-03-09,Plo-TS859,H/42448,2026-03-09 10:32:17,2026-03-09 10:57:06,-24.816667,1163,1009
1171,8180.0,"Krüger, Alexander",1651,0,0,502959.180,0.000,0.0,"53,52262","9,98941","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",TS859 - Fahrzeugdetails,2026-03-10,Plo-TS859,H/42459,2026-03-10 11:51:11,2026-03-10 11:51:14,-0.050000,1171,1016
1207,8197.0,"Hrzuska, Krzystof",1651,323,0,805964.005,0.000,0.0,"53,5226","9,98945","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",WL-PL431 - Fahrzeugdetails,2026-03-09,WL-PL431,H/42480,2026-03-09 07:46:50,2026-03-09 07:52:35,-5.750000,1207,1046
1414,8205.0,"Borrs, Thomas",1651,250,0,0.000,0.000,0.0,"53,57474","10,03696","DE - 22081 Hamburg (Barmbek-Süd), Holsteinisch...",Plö-TS853 - Fahrzeugdetails,2026-03-04,Plö-TS853,H/42408,2026-03-04 08:04:32,2026-03-04 08:05:04,-0.533333,1414,1233
1492,8180.0,"Krüger, Alexander",1651,78,3,502852.370,0.000,0.0,"53,5226","9,98913","DE - 20457 Hamburg (Hamburg-Mitte), Brandenbur...",TS859 - Fahrzeugdetails,2026-03-06,Plo-TS859,H/42432,2026-03-06 11:00:07,2026-03-06 11:00:47,-0.666667,1492,1301

In [67]:
df_merged2[df_merged2['Standzeit_min'] > 0] \
    .groupby('Fahrername')['Standzeit_min'] \
    .describe() \
    .round(2) \
    .sort_values('mean', ascending=False)

,count,mean,std,min,25%,50%,75%,max
Fahrername,,,,,,,,
"Szmajdewicz, Marcin",62.0,53.28,57.15,0.02,0.11,39.29,89.48,249.58
"Teme, Abdoulaye",29.0,49.79,75.89,0.02,0.02,24.82,62.35,364.65
"Giewon, Mariusz",162.0,36.57,41.52,0.02,10.83,26.28,46.79,266.67
"Hesse, Sven-Erik",30.0,34.77,43.06,0.03,0.07,5.33,70.37,149.33
"Calina, Florin Alexandru",56.0,30.70,31.12,0.02,0.08,30.72,51.71,115.57
"Krüger, Alexander",117.0,27.05,29.44,0.02,0.17,15.42,48.05,97.48
"Oelschlaeger, Marcel",74.0,25.50,31.93,0.02,0.69,10.79,33.28,107.57
"Ledwina, Jens",154.0,18.63,39.28,0.03,2.26,3.83,7.35,306.78
"Jorczik, Christian",86.0,13.22,28.58,0.02,0.02,0.02,0.30,104.42
"Hrzuska, Krzystof",47.0,5.62,10.78,0.02,0.02,0.02,0.41,36.42
"Borrs, Thomas",124.0,4.77,9.45,0.02,1.60,2.71,4.45,95.90

In [68]:
df_merged2[
    (df_merged2['Standzeit_min'] > 0) & 
    (df_merged2['Standzeit_min'] < 2)
] \
.groupby('Fahrername')['Standzeit_min'] \
.count() \
.reset_index() \
.rename(columns={'Standzeit_min': 'Anzahl_unter_2min'}) \
.sort_values('Anzahl_unter_2min', ascending=False)

                  Fahrername  Anzahl_unter_2min
5         Jorczik, Christian                 68
0              Borrs, Thomas                 43
4          Hrzuska, Krzystof                 36
6          Krüger, Alexander                 36
7              Ledwina, Jens                 30
2            Giewon, Mariusz                 27
1   Calina, Florin Alexandru                 23
9        Szmajdewicz, Marcin                 21
8       Oelschlaeger, Marcel                 19
3           Hesse, Sven-Erik                 13
10           Teme, Abdoulaye                 12

In [69]:
alle_stopps = df_merged2[df_merged2['Standzeit_min'] > 0] \
    .groupby('Fahrername')['Standzeit_min'].count().rename('Gesamt')

unter_1min = df_merged2[
    (df_merged2['Standzeit_min'] > 0) & 
    (df_merged2['Standzeit_min'] < 1)
].groupby('Fahrername')['Standzeit_min'].count().rename('Unter_1min')

pd.concat([alle_stopps, unter_1min], axis=1) \
  .fillna(0) \
  .assign(Anteil_pct=lambda x: (x['Unter_1min'] / x['Gesamt'] * 100).round(1)) \
  .sort_values('Anteil_pct', ascending=False)

                          Gesamt  Unter_1min  Anteil_pct
Fahrername
Jorczik, Christian            86          68        79.1
Hrzuska, Krzystof             47          36        76.6
Hesse, Sven-Erik              30          13        43.3
Teme, Abdoulaye               29          12        41.4
Calina, Florin Alexandru      56          23        41.1
Szmajdewicz, Marcin           62          20        32.3
Krüger, Alexander            117          36        30.8
Oelschlaeger, Marcel          74          19        25.7
Giewon, Mariusz              162          27        16.7
Borrs, Thomas                124          14        11.3
Ledwina, Jens                154          12         7.8

In [70]:
df_merged2[df_merged2['Standzeit_min'] >= 0]['Standzeit_min'].describe()

count    1001.000000
mean       23.323743
std        38.177664
min         0.000000
25%         0.066667
50%         4.450000
75%        32.900000
max       364.650000
Name: Standzeit_min, dtype: float64

In [71]:
df_merged2[df_merged2['Standzeit_min'] >= 0] \
    .groupby('Fahrername')['Standzeit_min'] \
    .describe() \
    .round(2)

,count,mean,std,min,25%,50%,75%,max
Fahrername,,,,,,,,
"Borrs, Thomas",128.0,4.62,9.34,0.00,1.60,2.59,4.44,95.90
"Calina, Florin Alexandru",61.0,28.19,30.98,0.00,0.07,15.97,50.95,115.57
"Giewon, Mariusz",162.0,36.57,41.52,0.02,10.83,26.28,46.79,266.67
"Hesse, Sven-Erik",30.0,34.77,43.06,0.03,0.07,5.33,70.37,149.33
"Hrzuska, Krzystof",48.0,5.50,10.70,0.00,0.02,0.02,0.40,36.42
"Jorczik, Christian",111.0,10.24,25.73,0.00,0.02,0.02,0.10,104.42
"Krüger, Alexander",121.0,26.16,29.35,0.00,0.12,13.67,47.83,97.48
"Ledwina, Jens",154.0,18.63,39.28,0.03,2.26,3.83,7.35,306.78
"Oelschlaeger, Marcel",95.0,19.86,30.08,0.00,0.02,5.62,25.52,107.57
"Szmajdewicz, Marcin",62.0,53.28,57.15,0.02,0.11,39.29,89.48,249.58
"Teme, Abdoulaye",29.0,49.79,75.89,0.02,0.02,24.82,62.35,364.65

In [75]:
import plotly.io as pio
import plotly.graph_objects as go
import plotly.express as px
import json
pio.templates.default = "plotly_white"
df_plot = df_merged2[df_merged2['Standzeit_min'] >= 0].copy()

#Boxplot

fig_box = px.box(
    df_plot,
    x='Fahrername',
    y='Standzeit_min',
    title='Standzeiten pro Fahrer<br><span style="font-size:18px;font-weight:normal;">Median, Quartile und Ausreißer</span>',
    color_discrete_sequence=['#00498b']  
)
fig_box.update_xaxes(title_text='Fahrer')
fig_box.update_yaxes(title_text='Standzeit (min)')
fig_box.show()